services:

  back:
    image: ylorklan/gamebotsbackimage:0.0.1
    container_name: backend_container
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/db
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=dbpass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"
    volumes:
      - ./local_images:/app/images
    depends_on:
      - db

  front:
    image: ylorklan/gamebotsfrontimage:0.0.1
    container_name: frontend_container
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - back

  db:
    image: postgres:16.3
    container_name: postgres_container
    restart: always
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
      - POSTGRES_DB=db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgres/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  pg-admin:
    image: dpage/pgadmin4:8.10
    container_name: pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=adminpass
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"
    depends_on:
      - db

  sonarqube:
    container_name: sonarqube
    image: sonarqube
    environment:
      - SONARQUBE_JDBC_USERNAME=sonarqube
      - SONARQUBE_JDBC_PASSWORD=sonarpass
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/db
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    ports:
      - "9000:9000"

volumes:
  pg_data:
  sonarqube_database_data:
  sonarqube_bundled-plugins:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_database:
  sonarqube_extensions: