name: Integration and Deployment Continue

run-name: ${{ github.actor }} has pushed code

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [ "21" ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: "temurin"

      - name: Create certs directory
        run: mkdir -p src/main/resources/certs

      - name: Add private.pem from GitHub Secret
        run: echo "${{ secrets.PRIVATE_PEM_CONTENT }}" > src/main/resources/certs/private.pem

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run Checkstyle
        run: mvn checkstyle:checkstyle

      - name: Run tests
        run: mvn test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.CD_DOCKER_USERNAME }}
          password: ${{ secrets.CD_DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.CD_DOCKER_USERNAME }}/gamebotsbackimage:0.0.1
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.revision=0.0.1
            org.opencontainers.image.created=${{ github.event.head_commit.timestamp }}