name: Integration and Deployment Continue

run-name: ${{ github.actor }} has pushed code

on:
  push:
    branches:
      - docker
      - develop
  pull_request:
    branches:
      - docker
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run Checkstyle
        run: mvn checkstyle:check

      - name: Run unit tests
        run: mvn test

      - name: Build Docker image
        run: docker build -t gamebotsbackimage:0.0.1 .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.CD_DOCKER_USERNAME }}
          password: ${{ secrets.CD_DOCKER_PASSWORD }}

      - name: Tag Docker image
        run: docker tag gamebotsbackimage:0.0.1 ${{ secrets.CD_DOCKER_USERNAME }}/gamebotsbackimage:0.0.1

      - name: Push Docker image
        run: docker push ${{ secrets.CD_DOCKER_USERNAME }}/gamebotsbackimage:0.0.1
