name: Integration and Deployment Continue

run-name: ${{ github.actor }} has pushed code

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [ "21" ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: "temurin"

      - name: Create certs directory
        run: mkdir -p src/main/resources/certs

      - name: Add private.pem from GitHub Secret
        run: echo "${{ secrets.PRIVATE_PEM_CONTENT }}" > src/main/resources/certs/private.pem

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run Checkstyle
        run: mvn checkstyle:checkstyle

      - name: Run tests
        run: mvn test

      - name: Build Docker image
        if: matrix.os == 'ubuntu-latest'
        run: |
          docker buildx create --use
          docker buildx build --platform linux/arm64,linux/amd64 -t gamebotsbackimage:0.0.1 .

      - name: Login to Docker Hub
        if: matrix.os == 'ubuntu-latest'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.CD_DOCKER_USERNAME }}
          password: ${{ secrets.CD_DOCKER_PASSWORD }}

      - name: Tag Docker image
        if: matrix.os == 'ubuntu-latest'
        run: docker tag gamebotsbackimage:0.0.1 ${{ secrets.CD_DOCKER_USERNAME }}/gamebotsbackimage:0.0.1

      - name: Push Docker image
        if: matrix.os == 'ubuntu-latest'
        run: docker push ${{ secrets.CD_DOCKER_USERNAME }}/gamebotsbackimage:0.0.1
