name: Integration Continue

run-name: ${{ github.actor }} is learning GitHub Actions

on:
  push:
    branches:
      - docker
      - develop
  pull_request:
    branches:
      - docker
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16.2
        env:
          POSTGRES_USER: ${{secrets.CI_DB_USER}}
          POSTGRES_PASSWORD: ${{secrets.CI_DB_PASSWORD}}
          POSTGRES_DB: db
        ports:
          - 9254:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21.0.1
        uses: actions/setup-java@v3
        with:
          java-version: "21.0.1"
          distribution: "adopt"

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run Checkstyle
        run: mvn checkstyle:checkstyle
