name: Integration and Deployment Continue

run-name: ${{ github.actor }} as push his code

on:
  push:
    branches:
      - docker
      - develop
  pull_request:
    branches:
      - docker
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21.0.1
        uses: actions/setup-java@v3
        with:
          java-version: "21.0.1"
          distribution: "adopt"

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run Checkstyle
        run: mvn checkstyle:checkstyle

      - name: Run unitaires tests
        run: mvn test

      # - name: Build image
       # run: docker build -t gamebotsbackimage:0.0.1 .

      # - name: Login to dockerhub
        # run: docker login -u ${{secrets.CD_DOCKER_USERNAME}} -p ${{secrets.CD_DOCKER_PASSWORD}}

      # - name: Prepare to push to docker
        # run: docker tag gamebotsbackimage:0.0.1 ${{secrets.CD_DOCKER_USERNAME}}/gamebotsbackimage:0.0.1

      # - name: Push to docker
       # run: docker push ${{secrets.CD_DOCKER_USERNAME}}/gamebotsbackimage:0.0.1
